### ISSUE TITLE
Static configuration

### ISSUE THREAD

**Issue by bts368** [oshazard/apacman#1]
Would it be possible to implement a static configuration file? E.g. so avoid having to alias --noconfirm and --noedit, and instead edit /etc/apacman.conf as:

NOCONFIRM=yes
NOEDIT=yes

etc.?

**Comment by oshazard** [comment]
Okay, I'll work on that now.

**Comment by oshazard** [comment]
@bts368 
Completed and updated in [AUR](https://aur.archlinux.org/packages/apacman/).

Version 1.0
* Added optional config file support (/etc/apacman.conf)
* --config <file> alternate configuration file
* -v, --verbose show enabled options
* added apacman.conf manpage
* cleaned up apacman manpage
* cleaned up help

(Documentation took awhile)
