### ISSUE TITLE
Issues on installing local packages

### ISSUE THREAD

**Issue by helixarch** [oshazard/apacman#17]
It fails to install a local package, if at least one of its dependencies is in the AUR or it is a virtual package (like kernel26)

**Comment by oshazard** [comment]
@helixarch 
Have you run into this issue since AUR4?

**Comment by helixarch** [comment]
I did some tests. The result is that now it successfully installs a local package, if at least one of its dependencies is a virtual package. But it still fails to install a local package if at least one of its dependencies is a package that can be found only in AUR. I have also opened a new issue related to virtual packages, that I noticed  now.

**Comment by oshazard** [comment]
Fixed in **v2.3** (@1fcbecdc5af210465a9f7bd88f95b6ab2b2e0052)

**Comment by helixarch** [comment]
I just tested 2.3 for both issues I opened and now works great. Thank you a lot oshazard!
