### ISSUE TITLE
AUR 4

### ISSUE THREAD

**Issue by helixarch** [oshazard/apacman#18]
It needs AUR 4 support

**Comment by bts368** [comment]
there's fledgling support- you can change the URL's used in /etc/apacman.conf

RPCURL="https://aur.archlinux.org/rpc.php?type"
PKGURL="https://aur.archlinux.org"

These can be set to aur4.
HOWEVER, the compatibility fails as the output differs slightly. e.g.:
AUR3 (https://aur.archlinux.org/rpc.php?type=info&arg=dumpet):

    {"version":1,"type":"info","resultcount":1,"results":{"ID":79002,"Name":"dumpet","PackageBaseID":79002,"PackageBase":"dumpet","Version":"2.1-2","CategoryID":16,"Description":"A tool for debugging El Torito boot images.","URL":"https:\/\/fedorahosted.org\/dumpet\/","NumVotes":1,"OutOfDate":0,"Maintainer":"sanerb","FirstSubmitted":1392392790,"LastModified":1392392994,"License":"GPL2","URLPath":"\/packages\/du\/dumpet\/dumpet.tar.gz"}}


AUR4 (https://aur.archlinux.org/rpc.php?type=info&arg=dumpet):

    {"version":1,"type":"info","resultcount":1,"results":{"ID":184267,"Name":"dumpet","PackageBaseID":79002,"PackageBase":"dumpet","Version":"2.1-2","Description":"A tool for debugging El Torito boot images.","URL":"https:\/\/fedorahosted.org\/dumpet\/","NumVotes":1,"OutOfDate":0,"Maintainer":"sanerb","FirstSubmitted":1392392790,"LastModified":1433780379,"License":"GPL2","URLPath":"\/cgit\/aur.git\/snapshot\/dumpet.tar.gz","CategoryID":1,"Popularity":0}}

Here's what the diff looks like (piped through jshon):

    6c6
    <   "ID": 79002,
    ---
    >   "ID": 184267,
    11d10
    <   "CategoryID": 16,
    18c17
    <   "LastModified": 1392392994,
    ---
    >   "LastModified": 1433780379,
    20c19,21
    <   "URLPath": "\/packages\/du\/dumpet\/dumpet.tar.gz"
    ---
    >   "URLPath": "\/cgit\/aur.git\/snapshot\/dumpet.tar.gz",
    >   "CategoryID": 1,
    >   "Popularity": 0

@oshazard  what kind of changes need to be made to the parsing for this?

**Comment by bts368** [comment]
untested, but tada:

    diff --git a/apacman b/apacman
    index 703a1d7..73a3261 100755
    --- a/apacman
    +++ b/apacman
    @@ -408,7 +408,7 @@ abslink() {
     pkginfo() {
       if ! [[ -f "$tmpdir/$1.PKGBUILD" ]]; then
         pkgpath=$(pkglink $1)
    -    curl -Lfs "${pkgpath%/*}/PKGBUILD" > "$tmpdir/$1.PKGBUILD"
    +    curl -Lfs "${pkgpath%/*/*}plain/PKGBUILD?h=${1}" > "$tmpdir/$1.PKGBUILD"
         if [[ $2 ]]; then
           # rename for syntax highlighting
           cp "$tmpdir/$1.PKGBUILD" "$tmpdir/PKGBUILD"
    diff --git a/apacman.conf b/apacman.conf
    index 1f7f272..6d1e235 100644
    --- a/apacman.conf
    +++ b/apacman.conf
    @@ -36,8 +36,8 @@
     #downdir="/var/cache/pacman/pkg"
     #savedir="/var/cache/apacman/pkg"
     #editor="nano -w"
    -#RPCURL="https://aur.archlinux.org/rpc.php?type"
    -#PKGURL="https://aur.archlinux.org"
    +#RPCURL="https://aur4.archlinux.org/rpc.php?type"
    +#PKGURL="https://aur4.archlinux.org"
     #ABSURL="rsync.archlinux.org"
     
     #

someone want to test those changes for me?

**Comment by bts368** [comment]
nevermind, not quite- installing works, and -Ss, but not -Si. will edit the above diff when i have something that works.

**Comment by bts368** [comment]
also, i'm grabbing apacman and apacman-deps on aur4 for you- will be more than happy to transfer ownership, just noticed they weren't taken yet and didn't want them to go the way of the dodo.

**Comment by oshazard** [comment]
Thank you @bts368 . Merged.
I have a couple more changes to make and still need to migrate my packages to AUR4

**Comment by oshazard** [comment]
Wrote this quickly to migrate packages, might be useful for someone else:
https://gist.github.com/oshazard/370c7ed631af2181ee51

**Comment by oshazard** [comment]
ATTN: @helixarch @bts368 
* apacman 1.9 now in AUR4
* Defaults to AUR4 now
* Added a --legacy flag to use AUR3 for the meantime (until August)
