### ISSUE TITLE
Return on "Proceed with installation" does not

### ISSUE THREAD

**Issue by quite** [oshazard/apacman#21]
Hitting return on the prompt below does not in fact proceed -- despite the old school capital "Y" indicating that it should.

    Aur Targets    (1): foo
    :: Proceed with installation? [Y/n]

**Comment by oshazard** [comment]
@quite 
Thanks for reporting this. Yeah there was actually a bug where it was accepting any input, however I'll add the old behavior to the next release.

**Comment by quite** [comment]
Great.

**Comment by oshazard** [comment]
Fixed in version 2.1
