### ISSUE TITLE
error: no operation specified (use -h for help)

### ISSUE THREAD

**Issue by senorsmile** [oshazard/apacman#3]
when I do a simple 
  apacman -Syu
or even
  apacman -Syu --auronly

I now get the error: 
  error: no operation specified (use -h for help)

This started happening after upgrade from 0.9 to 1.0.

**Comment by senorsmile** [comment]
However, if I put anything after, it works.  E.g.:
apacman -Syu abcdefg

apacman -S dropbox seems to work just fine.  

Something changed with the parsing and introduced a bug?

**Comment by senorsmile** [comment]
It looks like the issue is on line 747:  

[[ $option != "searchinstall" && -z $packageargs ]] && err "${COLOR7}error:${ENDCOLOR} no operation specified (use -h for help)"

which will always err if there's no packageargs.  Not sure exactly what the intent was there.

**Comment by oshazard** [comment]
@senorsmile 
Yes, sorry about that. 
I'll fix that in the next update, working on feature request #2 at the moment.

**Comment by oshazard** [comment]
Fixed this and another bug (forced options) in [version 1.1](https://aur.archlinux.org/packages/apacman/)
