### ISSUE TITLE
"1 pacnew files found (0 added).  Update files now? (Y/n)" with no pacnew files

### ISSUE THREAD

**Issue by benoliver999** [oshazard/apacman#31]
This seems to happen on every upgrade since the last apacman update. Tested on several machines.

I can't find any pacnew files on the system, and hitting yes or no just makes the install process continue as if there were none (or as if I'd hit 'no' if there actually were some).

Is anyone else getting the same thing?

**Comment by oshazard** [comment]
@benoliver999 
It's not `apacman`. 

You must be using some sort of wrapper that is aliased to `pacman` to handle *.pacnew* files.

```
$ type -a pacman
```

**Comment by benoliver999** [comment]
Ahem... sorry about that. It's pacmatic - I completely forgot.

**Comment by oshazard** [comment]
Ah right `pacmatic`. Someone else had an issue with it before. **keenerd** isn't maintaining that one anymore either. 

If there are specific features from it you can't live without, then feel free to open a new issue, describe in detail the feature request(s) and I'll implement them (as option flags + config file but not default)

**Comment by benoliver999** [comment]
That's a generous offer. It would mainly be an option to print any new arch news, as well as a way to detect and edit pacnew/pacsave files - or leave them be.

Is it not drifting a little far from the 'aur wrapper' idea? I'm happy to file the feature requests if you think it's something that apacman might benefit from.

**Comment by oshazard** [comment]
I suppose that's true. [pacmatic](https://raw.githubusercontent.com/keenerd/pacmatic/master/pacmatic) is ~200 lines, so I didn't think it so bad. But a fork added to [apacman-utils](https://github.com/oshazard/apacman-utils) would be a better idea.
