### ISSUE TITLE
Put AUR packages in to /var/cache/pacman/pkg

### ISSUE THREAD

**Issue by justin8** [oshazard/apacman#33]
Currently when you install from the repo packages are cached as you would expect, but the AUR ones are not put here, so downgrading to an older version is much more painful than it should be.

**Comment by oshazard** [comment]
The AUR packages should be saved to */var/cache/apacman/pkg/*
Have you checked there? 

I did change the `.install` file a few versions ago, so it's possible that the directory is not being created with the correct permissions. 

Also see `man apacman.conf` if you'd like to set a different location (you'll need to make sure the permissions are set correctly)

**Comment by justin8** [comment]
That works, I didn't see that it saved them there. Keep up the good work!
