### ISSUE TITLE
doesn't install checkdepends if needed

### ISSUE THREAD

**Issue by senorsmile** [oshazard/apacman#4]
e.g. perl-expect has:
   checkdepends=('perl-test-exception>=0.32') 
in its PKGBUILD. 

makepkg fails without those being installed.  Not sure where the best place to insert this logic would be.  If I get time before the project owner fixes this, I'll put together something and submit a PR.

**Comment by oshazard** [comment]
I think it's a somewhat new PKGBUILD variable, I haven't come across it before. 
It's unclear what its purpose is. Seems to be somewhere between depends=() and optdepends=()

**Comment by oshazard** [comment]
Reading
```man PKGBUILD```
Seems to imply that packages in *checkdepends=()* are build deps but that running  **makepkg --nocheck** ignores these deps.

Based on this, it is my understanding that this should be handled by passing a new flag *--skipcheck* and without its presence add the contents of checkdepends to the list of packages to be installed.

**Comment by senorsmile** [comment]
According to the wiki, https://wiki.archlinux.org/index.php/PKGBUILD#checkdepends :

An array of packages this package depends on to run its test suite but are not needed at runtime. Packages in this list follow the same format as depends. These dependencies are only considered when the check() function is present and is to be run by makepkg.

I tested that package on a fresh vm with yaourt just to see what it would do, and it did just install the checkdepends.  

Since a package that has checkdepends will more than likely have a check() function for its preinstallation tasks, it would probably be safe to either: 
1. just install it
2. or install it if it's not already installed and then remove it

What do apacman do for builddepends?  I assume it should do the same action for checkdepends.

**Comment by oshazard** [comment]
@senorsmile 
Fixed! Thank you for the bug reports, please let me know if you find any other inconsistencies.

Version 1.2 changelog:
* Added checkdepends=() packages to deps
* --purgebuild remove unneeded build dependencies
* --skiptest skips installing check() unit test packages

**Comment by oshazard** [comment]
Oh, one thing I should point out: 
* Explicitly installed packages do not depend on *checkdepends* deps, therefore pacman's recursive remove (*-Rs*) will not uninstall them. They are installed using *pacman --asdeps <package>* so they **will** be considered orphans / unrequired deps (*-Qdt*). Lastly for the purposes of *--purgebuild* they are considered build deps.
