### ISSUE TITLE
Installing a package that is in the cache already still requires internet

### ISSUE THREAD

**Issue by justin8** [oshazard/apacman#52]
I was trying to install a package I had in my cache the other day while my internet was down, and apacman trys to connect out and has an error. I was running `apacman -S nwjs-bin --asdeps --needed` which if I used pacman instead would install almost instantly because it doesn't have to download any package databases, and it is local already.

**Comment by oshazard** [comment]
Still trying to find a good way to unit test this behavior...

✔  `firejail --net=none`
✘ `unshare` (lack of user namespaces in Arch Linux kernel)
