### ISSUE TITLE
Updating devel packages doesn't work anymore

### ISSUE THREAD

**Issue by sh4nks** [oshazard/apacman#60]
Hey,

When I try to update all my ``--devel`` packages that I have installed, it always finishes with "local database is up to date" which would not be true in this case because I know that I have installed several VCS packages. (also notice how curl exited)

```
$ apacman -Syu --devel
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Synchronizing aur database...
notice: curl exited with code 6             39  75 [######################----------------------] 52%
manpage: Couldn't resolve host. The given remote host was not resolved.
 aur                                        75  75 [############################################]100%
:: Starting full aur upgrade...
 local database is up to date
```

**Comment by justin8** [comment]
The curl exit code is due to an installed package that is no longer (or never was) in the AUR. I'll post a fix for that soon. But it's a red herring as far as the --devel breakage is concerned.

**Comment by oshazard** [comment]
This was actually two bugs. 

- The `$basepath` part of the URL was slicing off in the wrong place (affecting any package with a period in the name)
- The code for the `--devel` flag has not been maintained _at all_ since forking from `packer`. I'm adding an "extinct" message for packages that are no longer in AUR

**Comment by oshazard** [comment]
@sh4nks and @justin8 should be fixed now
