### ISSUE TITLE
--warn is ignored

### ISSUE THREAD

**Issue by petamem** [oshazard/apacman#77]
# apacman --warn -S intel-opencl-sdk

Aur Targets    (1): intel-opencl-sdk

:: Proceed with installation? [Y/n] Y
Edit intel-opencl-sdk PKGBUILD with $editor? [Y/n] n
Edit intel-opencl-sdk.install with $editor? [Y/n] n
==> Making package: intel-opencl-sdk 2016_6.2.0.1760-1 (Mon Oct 31 19:10:11 CET 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found intel_sdk_for_opencl_2016_6.2.0.1760_x64.tgz
==> Validating source files with sha256sums...
    intel_sdk_for_opencl_2016_6.2.0.1760_x64.tgz ... FAILED
==> ERROR: One or more files did not pass the validity check!

==> ERROR: the build failed
  -> Status
        failed (1): intel-opencl-sdk

My understanding of the docs would be that this should not have been fatal:

    --warn       - treat errors as non-fatal warnings

**Comment by oshazard** [comment]
The error above is not in the `apacman` codebase but from `makepkg`.
It can be resolved with the `--skipinteg` flag, which will pass-through to `makepkg` to skip the hash check.
