### ISSUE TITLE
libc++ missing

### ISSUE THREAD

**Issue by Orbsa** [oshazard/apacman#88]
I have libc++ installed as the dependencies require, but everytime i run apacman -Syu, it prints out 
```
: Synchronizing aur database...
:: There are 117 packages that provide libc++:
```
and then fails to update anything

Here's the the full bash debug:
http://pastebin.com/0Rvge879

**Comment by zamabe** [comment]
Removing the `aurpkglist()` function results in `command not found` lines, but otherwise fixes this.

**Comment by zamabe** [comment]
print debugging suggests the hang doesn't occur in aurpkglist, it happens when `selectprovider()` calls `pickone()`

**Comment by zamabe** [comment]
(Still print debugging) It does not appear to enter `pickone()`, it just hangs.

**Comment by zamabe** [comment]
Oooh, it appears that this might fix this issue:

```diff
diff --git a/apacman b/apacman
index a2c9a4c..0c32869 100755
--- a/apacman
+++ b/apacman
@@ -360,7 +360,7 @@ existsinaur() {
   regexmatch="$(echo $val | tr -dc '0-9a-z-.\n')"
   if [[ $val != $regexmatch ]]; then
      matches=$(aurpkglist "$val")
-     selectprovider "$val" $matches
+     selectprovider "$val" "${matches[@]}"
      if [[ $providepkg ]]; then
        eval "$2=\"$providepkg\"" 2>/dev/null
        chosenpkg="$providepkg"
@@ -605,6 +605,14 @@ aurbar() {
   fi
   printf "%s %3s%%\r" ${endbar} ${perc}
 }
+ 
+aurpkglist() {
+  if ! [[ -f "$tmpdir/packages.lst" ]]; then
+    curl -Lfs "$PKGURL/packages.gz" | gunzip > "$tmpdir/packages.lst"
+  fi
+
+  grep -E "$1" "$tmpdir/packages.lst" | sort
+}
 
 rpcinfo() {
   if ! [[ -f "$tmpdir/$1.info" ]]; then
```

**Comment by zamabe** [comment]
That patch solves `-Syu` (for me?), but regex mode won't allow me to find the package to install it to begin with. Separate issues.

**Comment by zamabe** [comment]
Aaaand the code is being removed with regex mode anyway. Fun distraction.

**Comment by zamabe** [comment]
Deleted my fork pull request #91 was based on. Posting the patch here because relevant issue.

[0001-Remove-regex-mode.patch.txt](https://github.com/oshazard/apacman/files/1083132/0001-Remove-regex-mode.patch.txt)
